name: driver_monitoring_system
description: Driver drowsiness detection and monitoring system android application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.3.3
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  lottie: ^1.3.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  location: ^4.4.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  flutter_tts: ^3.3.3
  syncfusion_flutter_gauges: ^20.1.57
  numberpicker: ^2.1.1
  firebase_database: ^9.0.15
  property_change_notifier: ^0.3.0
  provider: ^6.0.3

  video_player: ^2.4.4
  flutter_mjpeg: ^2.0.1

  audioplayers: ^1.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/animations/go-to-my-location-button.json
    - lib/assets/animations/map-type-button.json
    - lib/assets/animations/
    - lib/assets/
    - assets/

